export enum TRACEABILITY_CONSTANTS {
    PRODUCT_SUPPLY_CHAIN_LIST = 'productSupplyChainList',
    SUBMIT = 'Submit',
    SUPPLIER_ASSOCIATION_STATUS = 'supplierAssociationStatus',
    PROVIDE_MYSELF = 'I will provide myself',
    SUPPLY_CHAIN = 'supplyChain',
    DATA = 'data',
    MAPPINGS = 'mappings',
    SUPPLIER_VERIFICATION_STATUS = 'supplier_verification_status',
    SUPPLIER_ASSOCIATION_STATUS_KEY = 'supplier_association_status',
    REQUIRED_FIELD = 'Required Field',
    PLEASE_UPDATE_THE_ARTICLE_NAME = 'Please update the article name',
    SUCCESS = 'Success',
    FAILED = 'Failed',
    CONFIRM_SUBMITTING = 'Confirm Submitting',
    ARTICLE = 'Article',
    SUPPLIER = 'Supplier',
    RAW_MATERIALS_WITHOUT_SPACE = 'RAW_MATERIALS',
    SUPPLY_CHAIN_ARTICLE = 'supplyChainArticle',
    PO_NUMBER = 'poNumber',
    RAW_MATERIAL_WITH_SPACE = 'Raw Material',
    REQUEST_SUBMITTED_SUCCESSFULLY = 'Request Submitted Successfully',
    I_DO_NOT_WISH_TO_PROVIDE = "I don't wish to provide",
    SNA_CANNOT_DISCLOSE = 'SNA_CANNOT_DISCLOSE',
    UN_INVITED = 'UN_INVITED',
    SEARCH_RESPONSE = 'searchResponse',
    FREE_HAND = 'freeHand'
}
